### ISSUE TITLE
CMake Error: Could not create named generator -DCMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by DoubleMice** [GoSSIP-SJTU/TripleDoggy#4]
move the -G option after "-DCMAKE_BUILD_TYPE=Release" works for me.
`cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../llvm`

**Comment by why1988seu** [comment]
CMake Error: The source directory "/data/clang/llvm" does not appear to contain CMakeLists.txt.
